name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [20, 22, 24]
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        shell: bash
      - run: npm run dist:ci
        shell: bash
      - run: npm run example:install
        shell: bash
      - run: npm run example:test:unit
        shell: bash
      - run: npm run example:test:cy:run
        shell: bash
